<?php

return [
    'default' => 'classic',
    'templates' => [
        'classic' => [
            'slug' => 'classic',
            'name' => 'Classic',
            'description' => 'Mood / What I did / Thoughts & Plans',
            'sections' => [
                [
                    'key' => 'mood',
                    'title_en' => 'Mood',
                    'title_ja' => '気分',
                    'placeholder_en' => "e.g., ちょっと疲れたけど I'm feeling pretty good.",
                    'placeholder_ja' => '例）ちょっと疲れたけど I feel pretty good.',
                    'order' => 1,
                    'input_type' => 'textarea',
                ],
                [
                    'key' => 'what_i_did',
                    'title_en' => 'What I did',
                    'title_ja' => '今日やったこと',
                    'placeholder_en' => 'e.g., 午前はmeetingして、午後はカフェでreading.',
                    'placeholder_ja' => '例）午前はmeetingして、午後はカフェでreading.',
                    'order' => 2,
                    'input_type' => 'textarea',
                ],
                [
                    'key' => 'thoughts_plans',
                    'title_en' => 'Thoughts & Plans',
                    'title_ja' => '考えごと・明日の予定',
                    'placeholder_en' => 'e.g., 明日はgymに行って、そのあと友だちとdinner.',
                    'placeholder_ja' => '例）明日はgymに行って、そのあと友だちとdinner.',
                    'order' => 3,
                    'input_type' => 'textarea',
                ],
            ],
        ],
        'simple' => [
            'slug' => 'simple',
            'name' => 'Simple',
            'description' => 'Free writing only',
            'sections' => [
                [
                    'key' => 'free_writing',
                    'title_en' => 'Free writing',
                    'title_ja' => '自由に書く',
                    'placeholder_en' => 'e.g., 今日は忙しかったけど overallはgood.',
                    'placeholder_ja' => '例）今日は忙しかったけど overallはgood.',
                    'order' => 1,
                    'input_type' => 'textarea',
                ],
            ],
        ],
        'daily_log' => [
            'slug' => 'daily_log',
            'name' => 'Daily Log',
            'description' => 'Mood / Highlights / Challenges / Learnings / Tomorrow',
            'sections' => [
                [
                    'key' => 'mood',
                    'title_en' => 'Mood',
                    'title_ja' => '気分',
                    'placeholder_en' => 'e.g., 今日はlow energyだけど気分はok.',
                    'placeholder_ja' => '例）今日はlow energyだけど気分はok.',
                    'order' => 1,
                    'input_type' => 'textarea',
                ],
                [
                    'key' => 'highlights',
                    'title_en' => 'Highlights',
                    'title_ja' => '良かったこと',
                    'placeholder_en' => 'e.g., 夕方に友だちとcoffeeしてrelaxできた.',
                    'placeholder_ja' => '例）夕方に友だちとcoffeeしてrelaxできた.',
                    'order' => 2,
                    'input_type' => 'textarea',
                ],
                [
                    'key' => 'challenges',
                    'title_en' => 'Challenges',
                    'title_ja' => '大変だったこと',
                    'placeholder_en' => 'e.g., 仕事がtoughで集中が切れた.',
                    'placeholder_ja' => '例）仕事がtoughで集中が切れた.',
                    'order' => 3,
                    'input_type' => 'textarea',
                ],
                [
                    'key' => 'learnings',
                    'title_en' => 'Learnings',
                    'title_ja' => '学び・気づき',
                    'placeholder_en' => 'e.g., small breaksすると集中が続くと気づいた.',
                    'placeholder_ja' => '例）small breaksすると集中が続くと気づいた.',
                    'order' => 4,
                    'input_type' => 'textarea',
                ],
                [
                    'key' => 'tomorrow',
                    'title_en' => 'Tomorrow',
                    'title_ja' => '明日やりたいこと',
                    'placeholder_en' => 'e.g., 明日はearlyに起きてwalkしたい.',
                    'placeholder_ja' => '例）明日はearlyに起きてwalkしたい.',
                    'order' => 5,
                    'input_type' => 'textarea',
                ],
            ],
        ],
    ],
];
